version: 2
jobs:
  build:
    docker:
      # TODO: Use library/swift:5.0 if available
      - image: library/swift:4.2.1
    steps:
      - checkout
      - run:
          name: Test
          command: swift test
